# Numpy

NumPy is a fundamental library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

Here are some key aspects of NumPy you should know about:

1. **Arrays**: The core of NumPy is its ndarray (n-dimensional array) object. These arrays can be created from Python lists, tuples, or other arrays using functions like `numpy.array()`.

2. **Array Attributes**: NumPy arrays have attributes like `shape` (dimensions of the array), `size` (total number of elements), `dtype` (data type of the elements), and more.

3. **Array Operations**: NumPy allows you to perform various mathematical and logical operations on arrays. You can perform element-wise operations, array broadcasting, array indexing, slicing, and more.

4. **Universal Functions (ufuncs)**: NumPy provides a wide range of mathematical functions that operate element-wise on arrays. These are called universal functions or ufuncs. Examples include `numpy.sin()`, `numpy.cos()`, `numpy.exp()`, etc.

5. **Array Indexing and Slicing**: NumPy arrays can be sliced and indexed like Python lists, but with additional capabilities for multi-dimensional arrays.

6. **Broadcasting**: NumPy can automatically perform operations on arrays of different shapes and sizes through broadcasting. This allows you to write code that looks similar to scalar operations but works with arrays of different shapes.

7. **Linear Algebra**: NumPy provides various functions for linear algebra operations like matrix multiplication (`numpy.dot()`), matrix inversion (`numpy.linalg.inv()`), eigenvalue decomposition (`numpy.linalg.eig()`), and more.

8. **Random Number Generation**: NumPy has a submodule called `numpy.random` that provides functions for generating random numbers and random arrays.

9. **File I/O**: NumPy provides functions for reading and writing data from/to disk. You can save NumPy arrays to disk using functions like `numpy.save()` and `numpy.savez()`, and load them back using `numpy.load()`.

10. **Performance**: NumPy operations are implemented in C, which makes them much faster than equivalent operations performed using Python lists. NumPy also supports vectorized operations, which further enhances performance.

To get started with NumPy, you can install it using pip:

```
pip install numpy
```

Once installed, you can import it into your Python code:

```python
import numpy as np
```

Then you can start using NumPy arrays and functions in your code. If you have any specific questions or topics you'd like to dive deeper into, feel free to ask!

Let's delve into each point with some code examples to illustrate them more clearly.

### 1. Arrays

NumPy arrays are the core data structure in NumPy. You can create arrays using the `numpy.array()` function.

In [1]:
import numpy as np

# Create a 1D array from a Python list
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1d)

# Create a 2D array from a list of lists
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(arr2d)

1D Array: [1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2. Array Attributes

NumPy arrays have several attributes to describe their shape, size, and data type.

In [2]:
# Shape of the array
print("Shape of arr2d:", arr2d.shape)

# Size of the array (total number of elements)
print("Size of arr2d:", arr2d.size)

# Data type of the elements
print("Data type of arr2d:", arr2d.dtype)

Shape of arr2d: (3, 3)
Size of arr2d: 9
Data type of arr2d: int32


### 3. Array Operations

You can perform various mathematical operations on NumPy arrays.

In [3]:
# Element-wise addition
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Element-wise addition:", arr1 + arr2)

# Array multiplication
print("Array multiplication:", arr1 * arr2)

Element-wise addition: [5 7 9]
Array multiplication: [ 4 10 18]


### 4. Universal Functions (ufuncs)

NumPy provides many mathematical functions that can operate element-wise on arrays.

In [4]:
# Calculate sine of each element
print("Sine of arr1:", np.sin(arr1))

# Calculate exponential of each element
print("Exponential of arr2:", np.exp(arr2))

Sine of arr1: [0.84147098 0.90929743 0.14112001]
Exponential of arr2: [ 54.59815003 148.4131591  403.42879349]


### 5. Array Indexing and Slicing

You can access elements of NumPy arrays using indexing and slicing.


In [5]:
# Access elements using indexing
print("First element of arr1:", arr1[0])

# Slicing
print("Sliced array:", arr1[1:3])

First element of arr1: 1
Sliced array: [2 3]


### 6. Broadcasting

NumPy allows you to perform operations on arrays of different shapes and sizes.

In [6]:
# Broadcasting scalar to array
print("Broadcasting scalar:", arr1 + 1)

# Broadcasting arrays of different shapes
arr3 = np.array([[1], [2], [3]])
print("Broadcasting arrays:")
print(arr2d + arr3)

Broadcasting scalar: [2 3 4]
Broadcasting arrays:
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


### 7. Linear Algebra

NumPy provides functions for various linear algebra operations.

In [7]:
# Matrix multiplication
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print("Matrix multiplication:")
print(np.dot(mat1, mat2))

Matrix multiplication:
[[19 22]
 [43 50]]


### 8. Random Number Generation

NumPy provides functions for generating random numbers and arrays.


In [8]:
# Generate a random array of shape (2, 3)
random_array = np.random.rand(2, 3)
print("Random array:")
print(random_array)

Random array:
[[0.94491725 0.21502842 0.63525034]
 [0.18050184 0.65916968 0.63908976]]


### 9. File I/O

NumPy allows you to save and load arrays from/to disk.

In [9]:
# Save array to a file
np.save('my_array.npy', arr1)

# Load array from file
loaded_array = np.load('my_array.npy')
print("Loaded array:", loaded_array)

Loaded array: [1 2 3]


### 10. Performance

NumPy operations are implemented in C, making them much faster than equivalent operations using Python lists.

In [10]:
# Performance comparison
py_list = list(range(1000000))
np_array = np.array(py_list)

# Time taken to square each element using Python list
%timeit [x**2 for x in py_list]

# Time taken to square each element using NumPy array
%timeit np_array**2

204 ms ± 4.26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.63 ms ± 203 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


These examples should give you a good understanding of the key features and capabilities of NumPy. Experimenting with these concepts in your own code will deepen your understanding even further. Let me know if you have any questions!

Let's dive deeper into some additional features and functionalities of NumPy.

### 1. Reshaping Arrays
NumPy allows you to reshape arrays without changing their data. This can be useful when you need to change the dimensions of an array.

In [11]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape to a 2x3 array
reshaped_arr = arr.reshape(2, 3)
print("Reshaped array:")
print(reshaped_arr)


Reshaped array:
[[1 2 3]
 [4 5 6]]


### 2. Array Concatenation and Splitting
You can concatenate multiple arrays together or split a single array into multiple smaller arrays.

In [12]:
# Concatenate arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate([arr1, arr2])
print("Concatenated array:", concatenated_arr)

# Split array
split_arrays = np.split(concatenated_arr, 2)
print("Split arrays:", split_arrays)

Concatenated array: [1 2 3 4 5 6]
Split arrays: [array([1, 2, 3]), array([4, 5, 6])]


### 3. Aggregation Functions
NumPy provides functions for aggregating data in arrays, such as computing the sum, mean, minimum, and maximum.

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Compute sum of all elements
print("Sum:", np.sum(arr))

# Compute mean of all elements
print("Mean:", np.mean(arr))

# Compute minimum and maximum values
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))


Sum: 21
Mean: 3.5
Minimum: 1
Maximum: 6


### 4. Broadcasting Rules
Understanding broadcasting rules is essential in NumPy. Broadcasting allows NumPy to work with arrays of different shapes when performing arithmetic operations.



In [14]:
# Broadcasting scalar to array
arr = np.array([1, 2, 3])
result = arr + 1
print("Broadcasting scalar:", result)

# Broadcasting arrays with different shapes
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
result = arr1 + arr2
print("Broadcasting arrays:", result)



Broadcasting scalar: [2 3 4]
Broadcasting arrays: [[2 4 6]
 [5 7 9]]


### 5. Advanced Indexing and Masking
NumPy supports advanced indexing techniques like using arrays as indices and boolean masks to select elements from an array.

In [15]:
# Advanced indexing
arr = np.array([10, 20, 30, 40])
indices = np.array([0, 2])
print("Advanced indexing:", arr[indices])

# Boolean masking
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 2
print("Boolean masking:", arr[mask])


Advanced indexing: [10 30]
Boolean masking: [3 4 5]


### 6. Vectorization
Vectorization is a powerful feature of NumPy that allows you to apply operations to entire arrays at once, rather than looping over individual elements.

In [16]:
# Vectorized operations
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2
print("Vectorized operation:", result)


Vectorized operation: [ 1  4  9 16 25]


### 7. Linear Algebra Functions
NumPy provides a rich set of functions for linear algebra operations, such as matrix multiplication, eigenvalue decomposition, and singular value decomposition.

In [17]:
# Matrix multiplication
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
result = np.dot(mat1, mat2)
print("Matrix multiplication:", result)


Matrix multiplication: [[19 22]
 [43 50]]


### 8. Masked Arrays
Masked arrays are arrays that have a mask associated with them. The mask indicates which elements should be ignored in computations.

In [18]:
# Create a masked array
arr = np.ma.array([1, 2, 3, 4, 5], mask=[False, True, False, False, True])
print("Masked array:", arr)


Masked array: [1 -- 3 4 --]


These are just a few additional aspects of NumPy that you can explore. NumPy is a vast library with many functionalities, so don't hesitate to experiment and explore its capabilities further. 

Let's explore some more advanced features and techniques in NumPy:

### 1. Broadcasting with Advanced Indexing
You can combine broadcasting with advanced indexing to perform complex operations efficiently.

In [19]:
# Broadcasting with advanced indexing
arr = np.array([[1, 2, 3], [4, 5, 6]])
indices = np.array([0, 2])
result = arr[:, indices]  # Selecting columns 0 and 2
print("Broadcasting with advanced indexing:")
print(result)


Broadcasting with advanced indexing:
[[1 3]
 [4 6]]


### 2. Fancy Indexing
Fancy indexing allows you to use arrays of indices to access or modify specific elements of an array.

In [20]:
# Fancy indexing
arr = np.array([[1, 2], [3, 4], [5, 6]])
indices = np.array([0, 2])
result = arr[indices]  # Selecting rows at indices 0 and 2
print("Fancy indexing:")
print(result)


Fancy indexing:
[[1 2]
 [5 6]]


### 3. NumPy Data Types
NumPy supports various data types, including integers, floats, complex numbers, and more. You can specify the data type when creating arrays.

In [21]:
# Specifying data types
arr_int = np.array([1, 2, 3], dtype=np.int32)
arr_float = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print("Integer array:", arr_int)
print("Float array:", arr_float)


Integer array: [1 2 3]
Float array: [1. 2. 3.]


### 4. Structured Arrays
Structured arrays allow you to create arrays with compound data types, similar to structs in C.

In [22]:
# Structured arrays
data = np.array([(1, 'John', 25), (2, 'Jane', 30)], dtype=[('id', int), ('name', 'S10'), ('age', int)])
print("Structured array:")
print(data)


Structured array:
[(1, b'John', 25) (2, b'Jane', 30)]


### 5. Linear Algebra Decompositions
NumPy provides functions for various matrix decompositions like Singular Value Decomposition (SVD), QR decomposition, and Cholesky decomposition.

In [23]:
# Singular Value Decomposition (SVD)
arr = np.array([[1, 2], [3, 4]])
U, S, V = np.linalg.svd(arr)
print("SVD:")
print("U:", U)
print("S:", S)
print("V:", V)


SVD:
U: [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
S: [5.4649857  0.36596619]
V: [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


### 6. FFT and Signal Processing
NumPy offers functions for computing the Fast Fourier Transform (FFT) and various signal processing operations.

In [24]:
# Fast Fourier Transform (FFT)
signal = np.array([1, 2, 3, 4])
fft_result = np.fft.fft(signal)
print("FFT result:", fft_result)


FFT result: [10.+0.j -2.+2.j -2.+0.j -2.-2.j]


### 7. Masked Arrays for Data Cleaning
Masked arrays can be useful for data cleaning tasks where you need to handle missing or invalid values.

In [25]:
# Masked arrays for data cleaning
data = np.array([1, 2, -999, 4, 5])
masked_data = np.ma.masked_equal(data, -999)
print("Masked array:")
print(masked_data)


Masked array:
[1 2 -- 4 5]


### 8. Universal Functions (ufuncs) with Custom Functions
You can create custom functions and apply them element-wise to NumPy arrays using universal functions (ufuncs).

In [26]:
# Custom ufunc
def my_func(x):
    return x ** 2 + 1

arr = np.array([1, 2, 3])
result = my_func(arr)
print("Custom ufunc result:", result)


Custom ufunc result: [ 2  5 10]


These advanced features expand the capabilities of NumPy and make it a powerful tool for various scientific and numerical computing tasks. Experimenting with these features will deepen your understanding of NumPy and enhance your proficiency in using it.