# Numpy

----------------------------------------------------------------

## Part-1

In [2]:
import numpy as np

In [3]:
l = [1,2,3,4,5]

In [5]:
arr = np.array(l)

In [6]:
type(arr)

numpy.ndarray

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [9]:
arr1 = np.array([[1,2,3], [2,3,4]])

In [11]:
arr.ndim #tell type of the array

1

In [12]:
arr1.ndim

2

In [15]:
mat = np.matrix(l) # returns minimum 2 dimension

In [16]:
mat

matrix([[1, 2, 3, 4, 5]])

In [14]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [17]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [18]:
np.asanyarray(arr1)

array([[1, 2, 3],
       [2, 3, 4]])

In [19]:
arr

array([1, 2, 3, 4, 5])

In [20]:
a = arr

In [21]:
a

array([1, 2, 3, 4, 5])

In [22]:
arr

array([1, 2, 3, 4, 5])

In [23]:
arr[0] = 100 # wiil change for both pointers .....also called swallow copy

In [24]:
arr

array([100,   2,   3,   4,   5])

In [25]:
a

array([100,   2,   3,   4,   5])

In [26]:
b = np.copy(arr) # will create separate memory

In [27]:
b

array([100,   2,   3,   4,   5])

In [28]:
b[0] = 234 # will not affect arr or a ...... deep copy

In [29]:
b

array([234,   2,   3,   4,   5])

In [30]:
arr

array([100,   2,   3,   4,   5])

In [32]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [35]:
iterable = (i*i for i in range(5))

In [36]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [37]:
np.fromstring("23 45 56", sep = ' ')

array([23., 45., 56.])

In [38]:
np.fromstring("23,45,56", sep = ',')

array([23., 45., 56.])

In [39]:
arr 

array([100,   2,   3,   4,   5])

In [40]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [41]:
arr.size    # tell total element

5

In [42]:
arr1.size

6

In [43]:
arr.shape   # tell the rows and columns

(5,)

In [44]:
arr1.shape

(2, 3)

In [45]:
arr.dtype

dtype('int32')

In [46]:
arr1.dtype

dtype('int32')

------------------------------------------------------------------------------------

## Part-2

In [47]:
import numpy as np

In [48]:
list(range(5))

[0, 1, 2, 3, 4]

In [49]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [50]:
list(range(0.4, 10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [52]:
np.arange(.4, 10.4, 0.2)    # like a range function but can take float value

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [53]:
list(np.arange(.4, 10.4, 0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [55]:
np.linspace(1,5,20)     # generates dataset on scale range ....# divides equally into 20 divisions and return 20 values

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [57]:
np.logspace(1,5, 10)    #generates logarithmic data ....default base is 10

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [58]:
np.logspace(1,5, 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [59]:
np.zeros(5)     # create an array with 0

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.zeros((3,4, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [62]:
np.zeros((3, 4, 2, 3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [63]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [64]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
arr = np.ones((3,4))

In [66]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [67]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [69]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [70]:
np.eye(5)   #identity matrix....square matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [71]:
arr1 = np.eye(5)

In [72]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
import pandas as pd

In [74]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [75]:
np.random.rand(2,3)

array([[0.96289773, 0.06271855, 0.37274084],
       [0.49741275, 0.83306133, 0.822451  ]])

In [76]:
np.random.randn(2,3)    # for normally distributed dataset

array([[ 0.53794425,  1.33081041, -0.3358629 ],
       [ 2.98012456,  0.03772509,  1.40432234]])

In [77]:
np.random.randint(1,5,(3,4))

array([[1, 3, 2, 4],
       [4, 3, 1, 1],
       [1, 4, 2, 4]])

In [78]:
arr2 = np.random.randint(1,5,(3,4))

In [79]:
arr2

array([[1, 3, 1, 4],
       [2, 2, 2, 3],
       [2, 3, 2, 4]])

In [80]:
arr2.size

12

In [81]:
arr2.shape

(3, 4)

In [82]:
arr2.reshape(2, 6)      # should be multiple of size

array([[1, 3, 1, 4, 2, 2],
       [2, 3, 2, 3, 2, 4]])

In [83]:
arr2.reshape(3, 6)

ValueError: cannot reshape array of size 12 into shape (3,6)

In [84]:
arr2.reshape(4, 3)

array([[1, 3, 1],
       [4, 2, 2],
       [2, 3, 2],
       [3, 2, 4]])

In [85]:
arr2.reshape(4, -1)

array([[1, 3, 1],
       [4, 2, 2],
       [2, 3, 2],
       [3, 2, 4]])

In [86]:
arr2.reshape(4, -1456216)

array([[1, 3, 1],
       [4, 2, 2],
       [2, 3, 2],
       [3, 2, 4]])

In [87]:
arr2.reshape(2,2,3)

array([[[1, 3, 1],
        [4, 2, 2]],

       [[2, 3, 2],
        [3, 2, 4]]])

Filter data

In [88]:
arr1 = np.random.randint(1, 10, (5, 6))

In [89]:
arr1

array([[2, 2, 7, 4, 4, 5],
       [3, 6, 5, 9, 3, 3],
       [6, 4, 2, 9, 5, 6],
       [2, 7, 4, 6, 4, 2],
       [5, 1, 8, 9, 2, 3]])

In [92]:
arr1 > 5

array([[False, False,  True, False, False, False],
       [False,  True, False,  True, False, False],
       [ True, False, False,  True, False,  True],
       [False,  True, False,  True, False, False],
       [False, False,  True,  True, False, False]])

In [93]:
arr1[arr1 > 5]

array([7, 6, 9, 6, 9, 6, 7, 6, 8, 9])

In [94]:
arr1[0]

array([2, 2, 7, 4, 4, 5])

In [95]:
arr1[0, [0, 1]]

array([2, 2])

In [99]:
arr1[2:4, [2, 3,]]

array([[2, 9],
       [4, 6]])

In [100]:
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [101]:
arr1

array([[2, 1, 2],
       [1, 1, 2],
       [2, 2, 1]])

In [102]:
arr2

array([[2, 1, 2],
       [2, 1, 2],
       [2, 1, 1]])

In [103]:
arr1 + arr2 

array([[4, 2, 4],
       [3, 2, 4],
       [4, 3, 2]])

In [104]:
arr1 - arr2

array([[ 0,  0,  0],
       [-1,  0,  0],
       [ 0,  1,  0]])

In [105]:
arr1 * arr2         # index wise multiplication

array([[4, 1, 4],
       [2, 1, 4],
       [4, 2, 1]])

In [106]:
arr1@arr2       # gives matrix multiplication

array([[10,  5,  8],
       [ 8,  4,  6],
       [10,  5,  9]])

In [107]:
arr1/arr2

array([[1. , 1. , 1. ],
       [0.5, 1. , 1. ],
       [1. , 2. , 1. ]])

In [108]:
arr1/0

C:\Users\aliab\AppData\Local\Temp\ipykernel_13732\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

Broadcasting

In [110]:
arr = np.zeros((3,4))

In [111]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [112]:
arr+6      

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [113]:
a = np.array([1,2,3,4])

In [114]:
arr + a         # add will column wise

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [115]:
b = np.array([3,4,5])

In [116]:
arr + b         # to do this we have to rotate the array ... but we can not rotate the 1D array 

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [117]:
b = np.array([[3,4,5]])

In [118]:
b.T     # rotating 2D array

array([[3],
       [4],
       [5]])

In [119]:
arr + b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [120]:
arr1 = arr + b.T

In [121]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [122]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [123]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [124]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [125]:
np.min(arr1)

3.0

In [126]:
np.max(arr1)

5.0

--------------------------------------------------------------------------------------------------------

## Part-3

In [127]:
import numpy as np

Array Manipulation

In [129]:
arr = np.random.randint(1, 10, (4, 4))

In [130]:
arr 

array([[5, 8, 1, 5],
       [9, 5, 2, 1],
       [1, 4, 4, 9],
       [6, 2, 9, 1]])

In [131]:
arr.reshape(8, 2)

array([[5, 8],
       [1, 5],
       [9, 5],
       [2, 1],
       [1, 4],
       [4, 9],
       [6, 2],
       [9, 1]])

In [132]:
arr.T       # rotating i.e. row becomes column and vice-versa

array([[5, 9, 1, 6],
       [8, 5, 4, 2],
       [1, 2, 4, 9],
       [5, 1, 9, 1]])

In [133]:
arr.flatten()       #create 1D array

array([5, 8, 1, 5, 9, 5, 2, 1, 1, 4, 4, 9, 6, 2, 9, 1])

In [134]:
np.expand_dims(arr, axis=1)     #expanding dimension across column

array([[[5, 8, 1, 5]],

       [[9, 5, 2, 1]],

       [[1, 4, 4, 9]],

       [[6, 2, 9, 1]]])

In [135]:
np.expand_dims(arr, axis=0)         #expanding dimension across row

array([[[5, 8, 1, 5],
        [9, 5, 2, 1],
        [1, 4, 4, 9],
        [6, 2, 9, 1]]])

In [136]:
data = np.array([[1], [2], [3]])

In [138]:
data

array([[1],
       [2],
       [3]])

In [139]:
np.squeeze(data)        # convert to 1D

array([1, 2, 3])

In [140]:
np.repeat(data, 2)

array([1, 1, 2, 2, 3, 3])

In [141]:
np.repeat(data, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [145]:
np.roll(data, 3)

array([[1],
       [2],
       [3]])

In [143]:
np.roll(data, 2)

array([[2],
       [3],
       [1]])

In [147]:
np.diag(np.array([1,2,3,4]))    #puts the data diagonally

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Binary Operations

In [148]:
arr1 = np.random.randint(1,10, (3,4))
arr2 = np.random.randint(1,10, (3,4))

In [149]:
arr1

array([[4, 6, 5, 6],
       [1, 6, 3, 6],
       [7, 2, 8, 3]])

In [150]:
arr2

array([[2, 2, 4, 1],
       [2, 3, 7, 8],
       [5, 9, 5, 7]])

In [151]:
arr1+arr2

array([[ 6,  8,  9,  7],
       [ 3,  9, 10, 14],
       [12, 11, 13, 10]])

In [152]:
arr1-arr2

array([[ 2,  4,  1,  5],
       [-1,  3, -4, -2],
       [ 2, -7,  3, -4]])

In [153]:
arr1*arr2

array([[ 8, 12, 20,  6],
       [ 2, 18, 21, 48],
       [35, 18, 40, 21]])

In [154]:
arr1/arr2

array([[2.        , 3.        , 1.25      , 6.        ],
       [0.5       , 2.        , 0.42857143, 0.75      ],
       [1.4       , 0.22222222, 1.6       , 0.42857143]])

In [155]:
arr1**arr2

array([[     16,      36,     625,       6],
       [      1,     216,    2187, 1679616],
       [  16807,     512,   32768,    2187]])

In [156]:
~arr1

array([[-5, -7, -6, -7],
       [-2, -7, -4, -7],
       [-8, -3, -9, -4]])

In [157]:
arr1>arr2

array([[ True,  True,  True,  True],
       [False,  True, False, False],
       [ True, False,  True, False]])

String Operations

In [158]:
arr = np.array(['ali', 'abbas'])

In [159]:
arr

array(['ali', 'abbas'], dtype='<U5')

In [160]:
np.char.upper(arr)

array(['ALI', 'ABBAS'], dtype='<U5')

In [161]:
np.char.capitalize(arr)

array(['Ali', 'Abbas'], dtype='<U5')

In [162]:
np.char.title(arr)

array(['Ali', 'Abbas'], dtype='<U5')

Mathematical Functions

In [163]:
arr1

array([[4, 6, 5, 6],
       [1, 6, 3, 6],
       [7, 2, 8, 3]])

In [164]:
np.sin(arr1)

array([[-0.7568025 , -0.2794155 , -0.95892427, -0.2794155 ],
       [ 0.84147098, -0.2794155 ,  0.14112001, -0.2794155 ],
       [ 0.6569866 ,  0.90929743,  0.98935825,  0.14112001]])

In [165]:
np.cos(arr1)

array([[-0.65364362,  0.96017029,  0.28366219,  0.96017029],
       [ 0.54030231,  0.96017029, -0.9899925 ,  0.96017029],
       [ 0.75390225, -0.41614684, -0.14550003, -0.9899925 ]])

In [166]:
np.tan(arr1)

array([[ 1.15782128, -0.29100619, -3.38051501, -0.29100619],
       [ 1.55740772, -0.29100619, -0.14254654, -0.29100619],
       [ 0.87144798, -2.18503986, -6.79971146, -0.14254654]])

In [167]:
np.log10(arr1)

array([[0.60205999, 0.77815125, 0.69897   , 0.77815125],
       [0.        , 0.77815125, 0.47712125, 0.77815125],
       [0.84509804, 0.30103   , 0.90308999, 0.47712125]])

In [168]:
np.exp(arr1)

array([[5.45981500e+01, 4.03428793e+02, 1.48413159e+02, 4.03428793e+02],
       [2.71828183e+00, 4.03428793e+02, 2.00855369e+01, 4.03428793e+02],
       [1.09663316e+03, 7.38905610e+00, 2.98095799e+03, 2.00855369e+01]])

In [169]:
np.power(arr1, 2)

array([[16, 36, 25, 36],
       [ 1, 36,  9, 36],
       [49,  4, 64,  9]], dtype=int32)

In [170]:
np.mean(arr1)

4.75

In [171]:
np.median(arr1)

5.5

In [172]:
np.std(arr1)        # standard deviation

2.0463381929681126

In [173]:
np.var(arr1)        # variance

4.1875

In [174]:
np.min(arr1)

1

In [175]:
np.max(arr1)

8

Arithmetic Operation

In [176]:
arr1

array([[4, 6, 5, 6],
       [1, 6, 3, 6],
       [7, 2, 8, 3]])

In [177]:
arr2

array([[2, 2, 4, 1],
       [2, 3, 7, 8],
       [5, 9, 5, 7]])

In [178]:
arr1-arr2

array([[ 2,  4,  1,  5],
       [-1,  3, -4, -2],
       [ 2, -7,  3, -4]])

In [179]:
np.subtract(arr1, arr2)

array([[ 2,  4,  1,  5],
       [-1,  3, -4, -2],
       [ 2, -7,  3, -4]])

In [180]:
np.multiply(arr1, arr2)

array([[ 8, 12, 20,  6],
       [ 2, 18, 21, 48],
       [35, 18, 40, 21]])

In [181]:
np.mod(arr1, arr2)

array([[0, 0, 1, 0],
       [1, 0, 3, 6],
       [2, 2, 3, 3]])

In [182]:
np.power(arr1, arr2)

array([[     16,      36,     625,       6],
       [      1,     216,    2187, 1679616],
       [  16807,     512,   32768,    2187]])

In [183]:
np.sqrt(arr1)

array([[2.        , 2.44948974, 2.23606798, 2.44948974],
       [1.        , 2.44948974, 1.73205081, 2.44948974],
       [2.64575131, 1.41421356, 2.82842712, 1.73205081]])

Statistical Functions

In [184]:
np.mean(arr1)

4.75

In [185]:
np.median(arr1)

5.5

In [186]:
np.std(arr1)

2.0463381929681126

---------------------------------------------------------------

## Part-4

Sort, Search & Countng Functions

In [187]:
import numpy as np

In [188]:
arr = np.array([4,2,8,5,3,9,12,56])

In [189]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [190]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [201]:
np.searchsorted(arr, 6)     # Find indices where elements should be inserted to maintain order

5

In [224]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [203]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [204]:
np.count_nonzero(arr1)

6

In [205]:
np.where(arr1>0)   # returns the index of satisfied conditions

(array([1, 2, 3, 4, 5, 9], dtype=int64),)

In [206]:
np.extract(arr1>2, arr1)

array([324, 645,  65,   6,   6, 234])

Byte Swapping

In [218]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [219]:
arr1.byteswap()

array([          0,  1140916224, -2063466496,  1090519040,   100663296,
         100663296,           0,           0,           0,  -369098752])

In [220]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [221]:
arr1.byteswap(True)

array([          0,  1140916224, -2063466496,  1090519040,   100663296,
         100663296,           0,           0,           0,  -369098752])

In [222]:
arr1

array([          0,  1140916224, -2063466496,  1090519040,   100663296,
         100663296,           0,           0,           0,  -369098752])

Copies & Views

In [225]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [227]:
a = np.copy(arr1)       # Deep Copy

In [228]:
a

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [229]:
b = arr1.view()         # it creates a swallow copy

In [230]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [231]:
b[0] = 234

In [232]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [233]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

Matrix Library

In [234]:
import numpy.matlib as nm

In [235]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [236]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [237]:
nm.eye(4)       # identity matrix

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Linear Algebra

In [238]:
arr1 = np.random.randint([[2,3], [4,5]])
arr2 = np.random.randint([[5,3], [2,5]])

In [239]:
arr1

array([[0, 0],
       [0, 1]])

In [240]:
arr2

array([[4, 1],
       [1, 3]])

In [241]:
np.dot(arr1, arr2)      # it is matrix multiplication

array([[0, 0],
       [1, 3]])

In [242]:
arr1@arr2           #  it is matrix multiplication

array([[0, 0],
       [1, 3]])

In [243]:
np.unique(arr1)

array([0, 1])

In [244]:
np.concatenate(arr1, arr2)

TypeError: only integer scalar arrays can be converted to a scalar index

In [245]:
np.flip(arr1)

array([[1, 0],
       [0, 0]])

In [246]:
np.argsort(arr1)        # It returns the indices that would sort an array

array([[0, 1],
       [0, 1]], dtype=int64)

In [247]:
np.transpose(arr1)      #Returns an array with axes transposed.

array([[0, 0],
       [0, 1]])

In [248]:
arr1

array([[0, 0],
       [0, 1]])