# Numpy Assignment

### Consider the below code to answer further questions:

In [11]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, the data type of variables list_ and array_list is different in Python. The code to print the data types of both the variables are as follows:

In [12]:
# Print the data type of list_
print("Data type of list_: ", type(list_))

Data type of list_:  <class 'list'>


In [13]:
# Print the data type of array_list
print("Data type of array_list: ", array_list.dtype)

Data type of array_list:  <U1


### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [14]:
# Print data type of each element in list_
for element in list_:
    print("Data type of element in list_: ", type(element))

Data type of element in list_:  <class 'str'>
Data type of element in list_:  <class 'str'>
Data type of element in list_:  <class 'str'>
Data type of element in list_:  <class 'str'>
Data type of element in list_:  <class 'str'>


In [15]:
# Print data type of each element in array_list
for element in array_list:
    print("Data type of element in array_list: ", element.dtype)

Data type of element in array_list:  <U1
Data type of element in array_list:  <U1
Data type of element in array_list:  <U1
Data type of element in array_list:  <U1
Data type of element in array_list:  <U1


### Q3. Considering the following changes in the variable, array_list:

In [16]:
array_list = np.array(object = list_, dtype = int)

### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

Yes, there will be a difference in the data type of the elements between list_ and array_list if you modify the code to:
```python
array_list = np.array(object = list_, dtype = int)
```

The code to print the data types of both the variables are as follows:

In [18]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
for element in list_:
    print("Data type of element in list_: ", type(element))

# Print data type of each element in array_list
for element in array_list:
    print("Data type of element in array_list: ", element.dtype)


Data type of element in list_:  <class 'str'>
Data type of element in list_:  <class 'str'>
Data type of element in list_:  <class 'str'>
Data type of element in list_:  <class 'str'>
Data type of element in list_:  <class 'str'>
Data type of element in array_list:  int32
Data type of element in array_list:  int32
Data type of element in array_list:  int32
Data type of element in array_list:  int32
Data type of element in array_list:  int32


### Consider the below code to answer further questions:

In [19]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

### Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape
### (ii) size

In [20]:
# (i) Shape
print("Shape of num_array:", num_array.shape)

Shape of num_array: (2, 3)


In [21]:
# (ii) Size
print("Size of num_array:", num_array.size)

Size of num_array: 6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
### [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [23]:
import numpy as np

# Create a 3x3 array of zeros using np.zeros
zero_array = np.zeros(shape=(3, 3))

print(zero_array)

# Print the shape and size of the array 
print("Shape of zero_array:", zero_array.shape)
print("Size of zero_array:", zero_array.size)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape of zero_array: (3, 3)
Size of zero_array: 9


### Q6. Create an identity matrix of shape (5,5) using numpy functions?
### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

The code to create a 5x5 identity matrix using NumPy functions:

In [24]:
import numpy as np

# Create a 5x5 identity matrix using np.eye
identity_matrix = np.eye(5)

# Print the identity matrix
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
